### ISSUE TITLE
Always shows the message like this:

### ISSUE THREAD

**Issue by mathxlee** [basarat/ntypescript#25]
>  Using ntypescript@2.1.0. This version may or may not be compatible with ts-loader.

The message always shows when I running my webpack.
Well, I use this compiler because the tsconfig.json is too complicated and I would get the 10082 error message so I chose this compiler, but shows the message above, please show me a way to correct the configurations, thanks.

**Comment by basarat** [comment]
> Using ntypescript@2.1.0. This version may or may not be compatible with ts-loader.

Because ts-loader maintains a list of *supported* `typescript` compiler options and this does not make the cut (this is a good warning to have :rose:)

Just use `npm install typescript@next` with ts-loader. You don't need `ntypescript` unless you are experimenting with the compiler API (nTypeScript is just TypeScript with a greater amount of API exposed as public) :rose:

**Comment by mathxlee** [comment]
> ERROR in error TS18002: The 'files' list in config file 'tsconfig.json' is empty.
> 
> ERROR in ../src/js/demo.ts
> Module build failed: error while parsing tsconfig.json

Hey there, I've followed your instructions and I get the error messages like above, and here is the configurations of tsconfig.json:

`{
    "compileOnSave": true,
    "compilerOptions": {
        "strictNullChecks": true
    }
}`
